### PR TITLE
Check in workflow

### PR DESCRIPTION
**Pull request by tlmader**
## #51 #50 (2/3) #54 (1/2) #56 #35 (2/4)

Major stuff here. 20 file changes (15 really though) is daunting, but at least scan the code and make sure it's readable. Point out areas of uncertainty, and I will improve documentation. This should complete the basis of collecting our visit data.

Also, I'm liking where the front-end testing is so far. I was able to make quite a bit of changes without running the client. Oh, and did I say we have a base client data service class now? 💯 

What it doesn't do: take time into account when pulling in visits to check if one is active. I think we should implement a way of ending a visit after a certain duration before attacking this, otherwise we will start piling up bad data. We can decide what to do with missing checkouts later. So yeah, even if your last check in was a year ago and left without an end, it will pull that for check out.

### Check in, no duplicate names

- [x] If no known volunteer is in the system, go to New Volunteer and add one to the system.
- [x] Click on the name form and verify autocomplete does not emit when empty.
- [x] Verify that autocomplete works properly as you type the volunteer's first or last name.
- [x] Verify Check In button is no longer disabled after typing the name of the volunteer.
- [x] Click Check In and refresh the page.
- [x] Verify the visit is logged accordingly on the visit history table.

### Check out, no duplicate names

- [x] Type that volunteer's name again in the name form.
- [x] Verify Check Out button is displayed and not disabled.
- [x] Click Check Out and refresh the page.
- [x] Verify the visit is updated accordingly on the visit history table.

### Check in, duplicate names

- [x] Add another volunteer to the system with the same name and different pet name.
- [x] Enter the name of that volunteer and verify the pet name form appears.
- [x] Click on the pet name form and verify autocomplete does not emit when empty.
- [x] Verify that autocomplete works properly as you type the volunteer's pet name.
- [x] Verify Check In is no longer disabled after typing the pet name of the volunteer.
- [x] Click Check In and refresh the page.
- [x] Verify the visit is logged accordingly on the visit history table.

### Check out, duplicate names

- [x] Type that volunteer's name and pet name again in the appropriate forms.
- [x] Verify Check Out button is displayed and not disabled.
- [x] Click Check Out and refresh the page.
- [x] Verify the visit is updated accordingly on the visit history table.

### CODE REVIEW

**Comment by harurang** [comment]
Unable to check-in. 
Console Error: 401 Conflict
Server Error: message: message: 'E11000 duplicate key error collection: admin.visits index: startAt_1_endAt_1_volunterId_1 dup key: { : null, : null, : null }',

**Comment by harurang** [comment]
Please make issues for any thing you feel this PR needs. i.e. Observing the state, what you were talking about in the 3rd paragraph of this PR or anything else you feel builds off this PR directly.

**Comment by harurang** [comment]
Don't forget to close issues and move PR's into the progress section of the kanban board.

**Comment by tlmader** [comment]
If you're getting 409, try dropping the collections from MongoDB.

**Comment by harurang** [comment]
Still unable to check in after dropping collection. Also, the visit dashboard has the following information before I even attempt to check in: 
7:33 pm to ...
Currently checked in!

**Comment by tlmader** [comment]
That just means there is existing data with a visit that hasn't been ended.

**Pull request merged**
